### ISSUE TITLE
Explanation please

### ISSUE THREAD

**Issue by yellowStaples07** [Krithika-p/Mountain-peak-sequence#1]
Can you explain why you are using (2^(n-1) - 2) formula for this problem statement?

**Comment by Krithika-p** [comment]
By the Binomial theorem and pascal triangle that 
Reference: https://www.math10.com/en/algebra/probabilities/binomial-theorem/binomial-theorem.html 
**(N-1)C0** + (N-1)C1 + (N-1)C2 + … + (N-1)C(N-2) + **(N-1)C(N-1)** = 2^(N-1) 
Therefore, our final answer is 
**2^(N-1) – (N-1)C0 – (N-1)C(N-1)** = 2^(N-1) – 2 (and the modulo).
